### ISSUE TITLE
dotenv in ConfigurationBean stops app from compiling (tomcat 9)

### ISSUE THREAD

**Issue by ManlyMan1** [LodLive/LodView#69]
Maven can't find the Dotenv class:

```
[ERROR] /C:/Users/konni/LodView/src/main/java/org/dvcama/lodview/conf/ConfigurationBean.java:[63,17] cannot find symbol
[ERROR]   symbol:   class Dotenv
[ERROR]   location: class org.dvcama.lodview.conf.ConfigurationBean

```
Importing it with **import io.github.cdimascio.dotenv.Dotenv;** helps to compile the webapp, but the app doesn't start anyway.

**Comment by renevoorburg** [comment]
Any news on this?

**Comment by KonradHoeffner** [comment]
I have no idea how that import statement got removed after being added in <https://github.com/LodLive/LodView/commit/954530ea8d3843332cd8dcbf232fad2c8567e10f>, maybe due to the order of merges.
Anyways I created a pull request to add it back in and also fix the runtime bug at <https://github.com/LodLive/LodView/pull/72>.
